config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :messages do
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :pics do 

  	member do
  		put "like", to: "pics#upvote"
  	end
  	member do
  		put "dislike", to: "pics#downvote"
  	end
  	resources :comments do
  	end

  end
  root 'pics#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :pic
  belongs_to :user

  

  validates_length_of :content, :minimum => 1
  
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
end

app/models/pic.rb
class Pic < ApplicationRecord
	acts_as_votable
	belongs_to :user
	has_many :comments


	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :pics
  has_many :comments
  has_many :messages
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :username, uniqueness: true
   

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  

  protected

  
  	def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])

    devise_parameter_sanitizer.permit(:sign_in, keys: [:username])
  
  	end
    
  
end

  
  

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :find_pic
	before_action :find_comment, only: [:destroy]

	def create
		@comment = @pic.comments.create(params[:comment].permit(:content))
		@comment.user_id = current_user.id
		@comment.save

		if @comment.save
			redirect_to pic_path(@pic)
		
		end
	end
	def destroy
		@comment.destroy
		redirect_to pic_path(@pic)

	end

	


	

	private

	def find_pic
     @pic= Pic.find(params[:pic_id])
 	end

 	def find_comment
 		@comment = @pic.comments.find(params[:id])
 	end

end

app/controllers/mailbox_controller.rb
class MailboxController < ApplicationController
	before_action :authenticate_user!
	def inbox
		@inbox = mailbox.inbox

	end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	before_action :authenticate_user!
	def index
		@messages= Message.all.order("created_at DESC")

	end
	def show
	end

	def new
		@message = current_user.messages.build
	end
	def create
		@message=current_user.pics.build(pic_params)
		
		redirect_to messages_path
	end
	private
	def message_params
     params.require(:message).permit(:content)
	end

end

app/controllers/pics_controller.rb
class PicsController < ApplicationController
	before_action :find_pic, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
	before_action :authenticate_user!, except: [:index, :show]

	def index
		@pics= Pic.all.order("created_at DESC")

	end
	

	def show
		@comments = Comment.where(pic_id: @pic).order("created_at DESC")
		

	end
	def new
		@pic = current_user.pics.build
	end
	def create
		@pic=current_user.pics.build(pic_params)
		if @pic.save
			redirect_to root_path
		else
			render 'new'
		end
	end
	def edit

	end

	def destroy
     @pic.destroy
     redirect_to root_path
	end
	def upvote

		@pic.upvote_by current_user
		redirect_to :back
	end
	def downvote

		@pic.downvote_by current_user
		redirect_to :back
	end


	def update
		if @pic.update(pic_params)
			redirect_to root_path
		else
			render 'edit'
		end


	end

	private
	def pic_params
     params.require(:pic).permit(:title, :image)
	end

	def find_pic
     @pic= Pic.find(params[:id])
 	end

	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/mailbox_helper.rb
module MailboxHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/views/comments/_comment.html.haml
.comment

	- @comments.each do |comment|
		= comment.content 
		- if current_user.id == comment.user.id
			= link_to [comment.pic,comment], method: :delete do
				%span.glyphicon.glyphicon-remove
		%br
		%small= comment.user.username
		%br
	= render 'comments/form'

app/views/comments/_form.html.haml
= simple_form_for ([@pic, @pic.comments.build]) do |f|

	= f.input :content,required: true, input_html: {class: 'form-control'}
	= f.button :submit, class: "btn btn-info"

app/views/layouts/application.html.haml
%html
%head
  
  %title DInstagram
  
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
  = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  = csrf_meta_tags

%body
  %nav.navbar.navbar-inverse
    .container
      .navbar-brand= link_to "DInstagram", root_path

      - if user_signed_in?
        %ul.nav.navbar-nav.navbar-left
          %li= link_to "New Pic", new_pic_path
          %li= link_to "Settings", edit_user_registration_path
          %li= link_to "Log Out", destroy_user_session_path, method: :delete
      - else
        %ul.nav.navbar-nav.navbar-left
          %li= link_to "Sign Up", new_user_registration_path
          %li= link_to "Log In", new_user_session_path

  .container
    -flash.each do |name, msg|
      =content_tag :div, msg, class: "alert alert-info"
    = yield

app/views/messages/index.html.haml
.container
	.messages
		
		- @messages.each do |message|
			%p= message.content
	

app/views/pics/_form.html.haml
= simple_form_for @pic, html: {multipart: true} do |f|
  - if @pic.errors.any?
    #errors
      %h2
      = pluralize(@pic.errors.count, "error")
      prevented this Pic from saving
      %ul
        - @pic.errors.full_message.each do |msg|
          %li= msg

  .form-group
    = f.input :image, input_html: {class: 'form-control'}
  .form-group
    = f.input :title, input_html: {class: 'form-control'}

  = f.button :submit, class: "btn btn-info"

app/views/pics/edit.html.haml
.col-md-8.col-md-offset-2
	.row
		.panel.panel-default
			.panel-heading
				%h1 Edit Pic
			.panel-body
				.current_image
					= image_tag @pic.image.url(:medium)
				= render 'form'

app/views/pics/index.html.haml
.col-md-6.col-md-offset-3
	#pics.transitions-enabled.centered
		- @pics.each do |pic|
			.panel.panel-default
				%p= pic.user.username
				= link_to (image_tag pic.image.url), pic
				%p= pic.title
				
				
				
	
			
    

app/views/pics/new.html.haml
.col-md-8.col-md-offset-2
	.row
		.panel.panel-default
			.panel-heading
				%h1 Post New Pic
			.panel-body
				= render 'form'

app/views/pics/show.html.haml
.col-md-6.col-md-offset-3
	.panel.panel-default
		.panel.heading.pic_image
			%p= @pic.user.username
			= image_tag @pic.image.url
		.panel-body

			%p= @pic.title
			
		.panel-footer
			.row
				.col-md-6

				.col-md-6

					.btn-group.pull-left
						- if user_signed_in?


							= link_to like_pic_path(@pic), method: :put, class: "btn btn-success" do
								%span.glyphicon.glyphicon-heart-empty
								=@pic.get_upvotes.size
							= link_to dislike_pic_path(@pic), method: :put, class: "btn btn-danger" do
								%span.glyphicon.glyphicon-remove-circle
								=@pic.get_downvotes.size
							-if @pic.user.id == current_user.id
								.btn-group.pull-left

									= link_to "Edit", edit_pic_path, class: "btn btn-info"
									= link_to "Delete", pic_path, method: :delete, data: { confirm: "Are you sure?"}, class: "btn btn-danger"
						- else

							= link_to "Back", root_path, class: "btn btn-info"
			.row
				.col-md-6
					
					= render 'comments/comment'

				